apiVersion: v1
kind: Service
metadata:
  name: mytouristweb
  labels:
    app: mytouristweb
spec:
  ports:
  - port: 80
    protocol: TCP
    name: web-port
  selector:
    app: mytouristweb
    tier: tourist-tier
  type: LoadBalancer
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: myconfigmapv1.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: touristdepl
  labels:
    app: touristdepl
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mytouristweb
      tier: tourist-tier
  template:
    metadata:
      labels:
        app: mytouristweb
        tier: tourist-tier
    spec: # Pod spec
      containers:
      - name: tourist-container
        image: jaimejr551/tourist-website
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: myconfigmapv1.0
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

